[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quant-factor-platform"
version = "0.1.0"
description = "Quantitative Factor Analytics & Visualization Platform for systematic trading strategies."
authors = [
    { name = "Zeshan Basaran", email = "zeshan.basaran@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    # Core data & numerical stack
    "pandas>=2.0",
    "numpy>=1.24",

    # Data ingestion
    "yfinance>=0.2.40",

    # Parquet I/O
    "pyarrow>=15.0",
    "fastparquet>=2024.2.0",

    # Visualization
    "matplotlib>=3.8",
    "streamlit>=1.36",
    "plotly>=5.20",

    # Database
    "SQLAlchemy>=2.0",
    "pymysql>=1.1.0",         # optional MySQL support
    "psycopg2-binary>=2.9",   # optional Postgres support

    # Reporting
    "xlsxwriter>=3.2",
    "openpyxl>=3.1",

    # Utilities
    "scipy>=1.12"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
namespaces = false

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
