# configs/default.yaml
universe:
  - SPY
  - TLT
  - AAPL
  - MSFT

rebal:
  freq: M   # M (month-end), W (weekly), Q (quarter-end)

factors:
  momentum:
    lookback_months: 6
    skip_recent_months: 1
  value:
    use_earnings_yield: true    # 1 / PE
  quality:
    metrics: ["roe", "de_ratio"]
