universe:
  symbols: [AAPL, MSFT, AMZN, GOOGL, META, NVDA, JPM, XOM, JNJ, PG]
  start: 2018-01-01
  end: 2023-12-31
rebal:
  frequency: M
factors:
  value:
    prefer: pe_ttm
    winsor: {lower_pct: 0.01, upper_pct: 0.99}
  momentum:
    lookback_months: 6
    skip_months: 1
    method: simple
    winsor: {lower_pct: 0.01, upper_pct: 0.99}
  quality:
    min_equity_abs: 1000
    clamp_de_ratio: 20.0
    winsor: {lower_pct: 0.01, upper_pct: 0.99}
portfolio:
  ranking:
    n_bins: 5
    best_is_high: true
  sleeve:
    long_bin: 5
    short_bin: 1
  exposure:
    gross: 1.0
    net: 0.0
risk:
  ic_horizon_days: 21
  ic_method: spearman
